### PR TITLE
Added backend code for the sign six position management

### PR DESCRIPTION
**Pull request by mikelasla**
Fixes issue #16 
Only was missing the backend code for the feature to work properly. Now when you sign in a certain position it not longer allows you to do it again. Also when the six positions are used, the action no longer appears.

### CODE REVIEW

**Comment by angelborroy-ks** [comment]
What about previously exiting documents?
What about changing position coordinates or the number of available positions?

It seems that this patch does not work in those scenarios.

**Comment by mikelasla** [comment]
You are right... This commit only adds what Share was already expecting

I'll try to find some time to contribute back with a complete solution. It should be a bootstrap patch that works on previously existing nodes with sign:signed aspect applied, right?
What should be done when a document contains more than 6 signatures? We need to think in a criteria for that...

**Comment by angelborroy-ks** [comment]
There is no need to think about such a criteria. 

You can retrieve PDF signatures from a PDF file to determine where are they located. So no other criteria (or artificial aspect) is required.

**Comment by angelborroy-ks** [comment]
I made some testing on this some time ago:
[https://github.com/angelborroy-ks/signature-position](https://github.com/angelborroy-ks/signature-position)

**Pull request closed without merging**
